# Generated by Django 4.1.5 on 2023-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_creation',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_creation',
            new_name='date_create',
        ),
    ]
